// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for the protobuf generated code
// In production, run: make proto to generate the actual file

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
)

type CreateVMRequest struct {
	Name     string
	CpuCores int32
	MemoryMb int32
	DiskGb   int32
	OsType   string
}

type VMActionRequest struct {
	Uuid string
}

type VMResponse struct {
	Uuid     string
	Name     string
	Status   string
	CpuCores int32
	MemoryMb int32
	DiskGb   int32
}

type ListVMsRequest struct{}

type ListVMsResponse struct {
	Vms []*VMResponse
}

type HypervisorServiceServer interface {
	CreateVM(context.Context, *CreateVMRequest) (*VMResponse, error)
	StartVM(context.Context, *VMActionRequest) (*VMResponse, error)
	StopVM(context.Context, *VMActionRequest) (*VMResponse, error)
	DeleteVM(context.Context, *VMActionRequest) (*VMResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
}

type UnimplementedHypervisorServiceServer struct{}

func (UnimplementedHypervisorServiceServer) CreateVM(context.Context, *CreateVMRequest) (*VMResponse, error) {
	return nil, nil
}
func (UnimplementedHypervisorServiceServer) StartVM(context.Context, *VMActionRequest) (*VMResponse, error) {
	return nil, nil
}
func (UnimplementedHypervisorServiceServer) StopVM(context.Context, *VMActionRequest) (*VMResponse, error) {
	return nil, nil
}
func (UnimplementedHypervisorServiceServer) DeleteVM(context.Context, *VMActionRequest) (*VMResponse, error) {
	return nil, nil
}
func (UnimplementedHypervisorServiceServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, nil
}

func RegisterHypervisorServiceServer(s *grpc.Server, srv HypervisorServiceServer) {}
